version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix" 
    versioning-strategy: "increase" 

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix" 
    versioning-strategy: "increase" 

  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"