# fly.toml app configuration file generated for backend-purple-snow-6522 on 2024-12-24T14:48:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'care.fi'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
