import type { Metadata } from "next";
import { Outfit as FontSans } from "next/font/google";
import "../styles/globals.css";

import { cn } from "@/lib/utils";
import NavBar from "@/components/ui/NavBar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fi">
      <body 
        className={cn(
          "min-h-screen bg-background font-sans antialiased p-8",
          fontSans.variable
        )}
      >
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 xl:px-12 max-w-8xl">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
