import type { Metadata } from "next";
import { Outfit as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils"
import NavBar from "@/components/ui/NavBar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fi">
      <body 
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
          <NavBar />
          {children}
        </body>
    </html>
  );
}
